version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9.1

    working_directory: /go/src/github.com/mdevilliers/lambda-deployer
    steps:
      - checkout
      - run: make get-build-deps
      - run: make check-vendor-licenses
      - run: make coverage
      - run: make all
      - persist_to_workspace:
          root: ./tmp/build
          paths:
            - ./lambda-uploader-darwin-amd64
            - ./lambda-uploader-linux-amd64
            - ./lambda-uploader-linux-arm
  lambda-build:
    docker:
      - image: eawsy/aws-lambda-go-shim:latest
        # the docker image for the shim has its own ideas the GOPATH should be
        environment:
          GOPATH: /go/
    working_directory: /go/src/github.com/mdevilliers/lambda-deployer
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace
      - run : make lambda-build-ci
      - persist_to_workspace:
          root: ./cmd/deployer
          paths:
            - ./lambda-deployer.zip
  release-to-github:
      docker:
        - image: circleci/golang:1.9.1
      steps:
       - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace
       - run: ls /tmp/workspace 
workflows:
  version: 2
  all:
    jobs:
      - build
      - lambda-build:
          requires:
            - build
      - release-to-github:
          requires:
            - build
            - lambda-build
