version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.1
    working_directory: /go/src/github.com/mdevilliers/lambda-deployer
    steps:
      - checkout
      - run: make get-build-deps
      - run: make check-vendor-licenses
      - run: make coverage
      - run: make all
      - persist_to_workspace:
          root: ./tmp/build
          paths:
            - ./lambda-uploader-darwin-amd64
            - ./lambda-uploader-linux-amd64
            - ./lambda-uploader-linux-arm
  lambda-build:
    docker:
      - image: circleci/golang:1.9.1
    working_directory: /go/src/github.com/mdevilliers/lambda-deployer
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run : make lambda-build
      - persist_to_workspace:
          root: ./tmp/build
          paths:
            - ./lambda-deployer.zip
  release-to-github:
      docker:
        - image: circleci/golang:1.9.1
      steps:
       - attach_workspace:
          at: /tmp/workspace
       - run: shasum -a 256 /tmp/workspace/* > /tmp/workspace/SHASUMS
       - run: go get github.com/tcnksm/ghr
       - run: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME `/tmp/workspace/lambda-uploader-linux-amd64 version` /tmp/workspace/
workflows:
  version: 2
  all:
    jobs:
      - build
      - lambda-build:
          requires:
            - build
      - release-to-github:
          requires:
            - build
            - lambda-build
          filters:
            branches:
              only: /release/
